name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to VPS
        env:
          SSH_PASSWORD: ${{ secrets.VPS_SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no yoseph@${{secrets.VPS_IP}} << 'EOF'
            cd /home/yoseph/source/bf-web
            git pull
            npm install
            npm run build
            sudo systemctl restart bfweb
          EOF
